//
export class ESInfo {
  public static readonly ES_PROP_INFO_PACKAGE_NAME = "packageName";
  public static readonly ES_PROP_INFO_VERSION = "version";
  public static readonly ES_PROP_INFO_ESKIT_VERSION = 'eskit_ver_code';
  public static readonly ES_PROP_INFO_CHANNEL = "channel";
  public static readonly ES_PROP_INFO_BRANCH = "branch";
  public static readonly ES_PROP_INFO_COMMIT_ID = "commitId";
  public static readonly ES_PROP_INFO_RELEASE_TIME = "releaseTime";
}

