const QUICKTVUI_TAG = 'quicktvui'
const LAYOUT_TAG = 'DebugLayout'
const TAG_CLICK = 'DebugClick'
const TAG_FASTLIST = 'DebugFastList'
const TAG_MediaSeries = 'DebugMediaSeries'
const TAG_REUSE = 'DebugReuse'
const TAG_FAST_EVENT = 'DebugEvent'
const TAG_TABS = 'DebugTabs'
const TAG_FOCUS = 'DebugFocus'
const TAG_STATE_DRAW = 'DebugStateDraw'
const TAG_PAGE = 'DebugPage'
const TAG_HOVER = 'DebugHover'
const TAG_SCROLL = 'DebugScroll'

export {
  QUICKTVUI_TAG as TAG_QUICKTVUI,
  LAYOUT_TAG as TAG_LAYOUT,
  TAG_FASTLIST,
  TAG_MediaSeries,
  TAG_CLICK,
  TAG_REUSE,
  TAG_FAST_EVENT,
  TAG_TABS,
  TAG_FOCUS,
  TAG_PAGE,
  TAG_STATE_DRAW,
  TAG_HOVER,
  TAG_SCROLL
}
