export enum QTPlayerEventProp {

  VALUE = "value",
  //
  PLAYER_ID = "id",
  //event
  PLAYER_STATE = "playerState",
  CURRENT_POSITION = "currentPosition",
  DURATION = "duration",

  INFO_TYPE = "infoType",
  INFO_CODE = "infoCode",
  INFO_MESSAGE = "infoMessage",

  ERROR_CODE = "errorCode",
  ERROR_MESSAGE = "errorMessage",

  PLAYER_WIDTH = "playerWidth",
  PLAYER_HEIGHT = "playerHeight",

  CODE = "code",
  MESSAGE = "message",

  //播放速率列表
  PLAY_RATE_LIST = "playRateList",
  PLAY_RATE = "playRate",

  //清晰度
  PLAY_DEFINITION_LIST = "definitionList",
  PLAY_DEFINITION = "definition",

  //画面比例
  PLAY_ASPECT_RATIO_LIST = "aspectRatioList",
  PLAY_ASPECT_RATIO = "aspectRatio",

  //解码
  PLAY_DECODE_LIST = "decodeList",
  PLAY_DECODE = "decode",

  //音量
  PLAY_LEFT_VOLUME = "leftVolume",
  PLAY_RIGHT_VOLUME = "rightVolume",

  //
  ANDROID_VUE_BRIDGE = "bridge",

  //是否可以点击
  PLAYER_CLICKABLE = "playerClickable",

  //百分比
  BUFFER_PERCENT = "percent",

}
