import { Config } from "./Config";

export const DefaultConfig: Config = {
  appId: 'debug',
  appName: '',
  appEntry: 'Application',
  appDebug: false,
  appEnableOAID: false,
          // http://test-api.extscreen.com/extscreenapi/api/extend_screen/v2/hili/client/tvinfo/harmony
  appBundleUri: 'https://api.extscreen.com/extscreenapi/api/extend_screen/v2/hili/client/tvinfo/harmony', //assets:///vue',
}